import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Subscription } from '@/hooks/useSubscriptions';
import { Capacitor } from '@capacitor/core';
import { shareBinaryFileNative } from './nativeShare';

export async function exportSubscriptionsPdf(subscriptions: Subscription[], currency: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ── Header band ──
  doc.setFillColor(99, 62, 255);
  doc.rect(0, 0, pageWidth, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Subzo', 14, 18);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Subscription Report', 14, 26);

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFontSize(9);
  doc.text(today, pageWidth - 14, 26, { align: 'right' });

  // ── Summary stats ──
  const active = subscriptions.filter((s) => s.status === 'active');
  const totalMonthly = active.reduce((sum, s) => {
    const amt = s.amount;
    if (s.billing_cycle === 'yearly') return sum + amt / 12;
    if (s.billing_cycle === 'weekly') return sum + amt * 4.33;
    return sum + amt;
  }, 0);

  const yStats = 48;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, yStats);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Active Subscriptions: ${active.length}`, 14, yStats + 8);
  doc.text(`Monthly Spend: ${currency} ${totalMonthly.toFixed(2)}`, 14, yStats + 15);
  doc.text(`Yearly Projection: ${currency} ${(totalMonthly * 12).toFixed(2)}`, 14, yStats + 22);

  // ── Table ──
  const headers = [['#', 'Name', 'Amount', 'Cycle', 'Category', 'Status', 'Next Renewal']];
  const rows = subscriptions.map((s, i) => [
    String(i + 1),
    s.name,
    `${currency} ${Number(s.amount).toFixed(2)}`,
    s.billing_cycle,
    s.category,
    s.status,
    new Date(s.next_renewal).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
  ]);

  autoTable(doc, {
    startY: yStats + 30,
    head: headers,
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: [99, 62, 255], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: [50, 50, 50] },
    alternateRowStyles: { fillColor: [245, 243, 255] },
    styles: { cellPadding: 4, lineColor: [220, 220, 230], lineWidth: 0.3 },
    columnStyles: { 0: { cellWidth: 10, halign: 'center' }, 2: { halign: 'right' }, 5: { halign: 'center' } },
    margin: { left: 14, right: 14 },
  });

  // ── Footer ──
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text('Generated by Subzo', 14, pageH - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageH - 10, { align: 'right' });
  }

  const fileName = `subscriptions-${new Date().toISOString().slice(0, 10)}.pdf`;

  if (Capacitor.isNativePlatform()) {
    const base64 = doc.output('datauristring').split(',')[1];
    await shareBinaryFileNative(fileName, base64);
  } else {
    doc.save(fileName);
  }
}
