
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=netflix.com&sz=64' WHERE name = 'Netflix';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=spotify.com&sz=64' WHERE name = 'Spotify';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=disneyplus.com&sz=64' WHERE name = 'Disney+';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=youtube.com&sz=64' WHERE name = 'YouTube Premium';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=amazon.com&sz=64' WHERE name = 'Amazon Prime';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=hulu.com&sz=64' WHERE name = 'Hulu';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=apple.com&sz=64' WHERE name = 'Apple Music';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=hbomax.com&sz=64' WHERE name = 'HBO Max';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64' WHERE name = 'Adobe Creative Cloud';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=microsoft.com&sz=64' WHERE name = 'Microsoft 365';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=dropbox.com&sz=64' WHERE name = 'Dropbox';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=google.com&sz=64' WHERE name = 'Google One';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=notion.so&sz=64' WHERE name = 'Notion';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=slack.com&sz=64' WHERE name = 'Slack';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=zoom.us&sz=64' WHERE name = 'Zoom';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=figma.com&sz=64' WHERE name = 'Figma';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=canva.com&sz=64' WHERE name = 'Canva';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=github.com&sz=64' WHERE name = 'GitHub Pro';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=1password.com&sz=64' WHERE name = '1Password';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=lastpass.com&sz=64' WHERE name = 'LastPass';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=nordvpn.com&sz=64' WHERE name = 'NordVPN';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=expressvpn.com&sz=64' WHERE name = 'ExpressVPN';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=grammarly.com&sz=64' WHERE name = 'Grammarly';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=todoist.com&sz=64' WHERE name = 'Todoist';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=evernote.com&sz=64' WHERE name = 'Evernote';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=headspace.com&sz=64' WHERE name = 'Headspace';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=calm.com&sz=64' WHERE name = 'Calm';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=peloton.com&sz=64' WHERE name = 'Peloton';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=strava.com&sz=64' WHERE name = 'Strava';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=nytimes.com&sz=64' WHERE name = 'New York Times';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=wsj.com&sz=64' WHERE name = 'Wall Street Journal';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=medium.com&sz=64' WHERE name = 'Medium';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=linkedin.com&sz=64' WHERE name = 'LinkedIn Premium';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=tinder.com&sz=64' WHERE name = 'Tinder';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=duolingo.com&sz=64' WHERE name = 'Duolingo Plus';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=skillshare.com&sz=64' WHERE name = 'Skillshare';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=masterclass.com&sz=64' WHERE name = 'MasterClass';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=coursera.org&sz=64' WHERE name = 'Coursera Plus';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=audible.com&sz=64' WHERE name = 'Audible';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=kindle.com&sz=64' WHERE name = 'Kindle Unlimited';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=crunchyroll.com&sz=64' WHERE name = 'Crunchyroll';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=twitch.tv&sz=64' WHERE name = 'Twitch';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=xbox.com&sz=64' WHERE name = 'Xbox Game Pass';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=playstation.com&sz=64' WHERE name = 'PlayStation Plus';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=nintendo.com&sz=64' WHERE name = 'Nintendo Switch Online';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=icloud.com&sz=64' WHERE name = 'iCloud+';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=apple.com/apple-tv-plus&sz=64' WHERE name = 'Apple TV+';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=deezer.com&sz=64' WHERE name = 'Deezer';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=tidal.com&sz=64' WHERE name = 'Tidal';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=paramount.com&sz=64' WHERE name = 'Paramount+';
UPDATE subscription_catalog SET logo_url = 'https://www.google.com/s2/favicons?domain=peacocktv.com&sz=64' WHERE name = 'Peacock';
